# COPYRIGHT Hello Corp. All Rights Reserved.
#
# Author: Haley
#

version: '2'

services:
  z4:
    extends:
      file: base/kafka-base.yaml
      service: zookeeper
    container_name: z4
    hostname: z4
    environment:
      # ID在集合中必须是唯一的并且应该有一个值在1-255之间。
      - ZOO_MY_ID=4
      # 组成ZK集合的服务器列表。客户端使用的列表必须与ZooKeeper服务器列表所拥有的每一个ZK服务器相匹配。
      # 有两个端口号：第一个是追随者用来连接领导者的，第二个是领导人选举。
      - ZOO_SERVERS=server.1=z1:2888:3888 server.2=z2:2888:3888 server.3=z3:2888:3888 server.4=z4:2888:3888 server.5=z5:2888:3888
    volumes:
       # 数据固化，将zookeeper产生的数据映射到本地，当zookeeper丢失等风险是不至于数据丢失
       - ./chainData/zookeeper/z4/:/data/
    extra_hosts:
      - "z1:39.104.77.237"
      - "z2:1.1.1.1"
      - "z3:2.2.2.2"
      - "z4:3.3.3.3"
      - "z5:4.4.4.4"
      - "k1:39.104.77.237"
      - "k2:1.1.1.1"
      - "k3:2.2.2.2"
      - "k4:3.3.3.3"
      - "k5:4.4.4.4"
